### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by salgo60** [WMPH/eph-historical-markers-map#1]
Thanks for excellent application ...

Error I found https://wmph.github.io/favicon.ico is missing I get a 404 in the console.log

>> Failed to load resource: the server responded with a status of 404 ()

**Comment by seav** [comment]
This error can be ignored. Browsers look for the favicon.ico file automatically and websites are not required to provide it. See https://en.wikipedia.org/wiki/Favicon

**Comment by seav** [comment]
For reference, the 404 error has been resolved by adding a `<link rel="icon">` in commit 7bf8c7b
